#+TITLE: Full System Configuration

* Introduction
* Table of Contents
:PROPERTIES:
:TOC: all
:END:
  -  [[#introduction][Introduction]]
  -  [[#table-of-contents][Table of Contents]]
  -  [[#installation][Installation]]
  -  [[#post-installation-setup][Post-Installation Setup]]
    -  [[#users--groups][Users & Groups]]
    -  [[#mirrors][Mirrors]]
    -  [[#aur-package-manager][AUR Package Manager]]
    -  [[#display-drivers][Display Drivers]]
    -  [[#xorg-server][Xorg Server]]
    -  [[#gnome--gdm][Gnome & GDM]]
    -  [[#themes][Themes]]
      -  [[#gnome-tweaks][Gnome Tweaks]]
      -  [[#gnome-theme][Gnome Theme]]
      -  [[#gdm-theme][GDM Theme]]
    -  [[#fonts][Fonts]]
    -  [[#extensions][Extensions]]
      -  [[#gsconnect][GSConnect]]
  -  [[#applications][Applications]]
    -  [[#zsh][Zsh]]
    -  [[#firefox][Firefox]]
    -  [[#thunderbird][Thunderbird]]
    -  [[#protonmail-bridge][ProtonMail Bridge]]
    -  [[#megasync][MEGASync]]
    -  [[#franz][Franz]]
    -  [[#keepassxc][KeePassXC]]
    -  [[#emacs][Emacs]]
    -  [[#ranger][Ranger]]
    -  [[#spotify][Spotify]]
    -  [[#vlc][Vlc]]
    -  [[#gnome-logs][Gnome Logs]]
  -  [[#programming-languages][Programming Languages]]
    -  [[#python][Python]]
      -  [[#flake8][flake8]]
      -  [[#jedi][jedi]]
      -  [[#numpy][numpy]]
      -  [[#nltk][nltk]]
      -  [[#elpy][elpy]]
      -  [[#autopep8][autopep8]]
      -  [[#rope][rope]]
      -  [[#yapf][yapf]]
      -  [[#virtualenv][virtualenv]]
      -  [[#jupyter][jupyter]]
      -  [[#ipython][ipython]]
      -  [[#matplotlib][matplotlib]]
    -  [[#c][C++]]
      -  [[#gcc][gcc]]
      -  [[#g][g++]]
      -  [[#make][make]]
      -  [[#cmake][cmake]]
      -  [[#clang][clang]]
      -  [[#irony][irony]]
      -  [[#silver-searcher-for-definition-jumps][silver searcher (for definition jumps)]]
      -  [[#cling][cling]]
    -  [[#javascript][JavaScript]]
      -  [[#npm][npm]]
      -  [[#typescript][typescript]]
      -  [[#tern][tern]]
      -  [[#yarn][yarn]]
      -  [[#meteor][meteor]]
      -  [[#mongodb][mongodb]]
      -  [[#revealjs][revealjs]]
      -  [[#prettier][prettier]]
    -  [[#java][Java]]
    -  [[#haskell][Haskell]]
    -  [[#mysql][MySQL]]
    -  [[#go][Go]]
    -  [[#latex][LaTeX]]
    -  [[#markdown][MarkDOWN]]
    -  [[#latex][Latex]]
  -  [[#optimizations][Optimizations]]
    -  [[#ssh-key][SSH Key]]
    -  [[#microcode][Microcode]]
    -  [[#silent-boot][Silent Boot]]
    -  [[#power-management][Power Management]]
      -  [[#battery-life][Battery Life]]
      -  [[#fan][Fan]]
      -  [[#cpu][CPU]]
    -  [[#printer][Printer]]
    -  [[#firewall][Firewall]]
    -  [[#vpn][VPN]]
    -  [[#startup-applications][Startup Applications]]
      -  [[#keepassxc][KeePassXc]]
      -  [[#franz][Franz]]
      -  [[#protonmail-bridge][ProtonMail Bridge]]
      -  [[#thunderbird][ThunderBird]]
      -  [[#emacs][Emacs]]
  -  [[#extras][Extras]]
    -  [[#python-cprofiler][Python cProfiler]]
    -  [[#markdown-template][Markdown Template]]
  -  [[#dropwizardhttpwwwdropwizardio102docs---the-web-framework-used][{Dropwizard}(http://www.dropwizard.io/1.0.2/docs/) - The web framework used]]
  -  [[#mavenhttpsmavenapacheorg---dependency-management][{Maven}(https://maven.apache.org/) - Dependency Management]]
  -  [[#romehttpsrometoolsgithubiorome---used-to-generate-rss-feeds][{ROME}(https://rometools.github.io/rome/) - Used to generate RSS Feeds]]
  -  [[#billie-thompson---initial-work---purpleboothhttpsgithubcompurplebooth][**Billie Thompson** - *Initial work* - {PurpleBooth}(https://github.com/PurpleBooth)]]
  -  [[#hat-tip-to-anyone-whose-code-was-used][Hat tip to anyone whose code was used]]
  -  [[#inspiration][Inspiration]]
  -  [[#etc][etc]]

* Installation

This section contains all the details for a basic arch linux installation
with windows 10 dual boot and general suggestions and links to either the
arch linux wiki or other sources.

1. Check your internet connection
#+BEGIN_SRC shell
ping 8.8.8.8
#+END_SRC
If no ping can be send go [[https://wiki.archlinux.org/index.php/Network_configuration#Network_interfaces][here]].

2. Load keyboard layout
#+BEGIN_SRC shell
loadkeys de-latin1
#+END_SRC

3. Verify boot mode
#+BEGIN_SRC shell
ls /sys/firmware/efi/efivars
#+END_SRC
If directory exists, the system was booted via UEFI mode, otherwise via BIOS.

4. Update system clock
#+BEGIN_SRC shell
timedatectl set-ntl true
#+END_SRC

5. Partition the disks
Create the following partitions considering /dev/sda1 and /dev/sda2 
already were created by the windows 10 system

|-----------+------+-------------------------|
| Device    | Size | Type                    |
|-----------+------+-------------------------|
| /dev/sda1 | 450M | Windows Recovery        |
| /dev/sda2 | 512M | EFI                     |
| /dev/sda3 | 20G  | Microsoft Base          |
| /dev/sda4 | 250G | Microsoft Basic (C)     |
| /dev/sda5 | 50G  | Root (linux filesystem) |
| /dev/sda6 | 16G  | Swap (linux swap)       |
| /dev/sda7 | 250G | Home (linux filesystem) |
|-----------+------+-------------------------|


6. Format the partitions
#+BEGIN_SRC sh
mkfs.ext4 /dev/sda3
mkfs.ext4 /dev/sda5
mkswap /dev/sda4
swapon /dev/sda4
#+END_SRC
7. Mount the file systems
#+BEGIN_SRC sh
mount /dev/sda3 /mnt
mkdir /mnt/home
mount /dev/sda5 /mnt/home
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
#+END_SRC
8. Install base packages
#+BEGIN_SRC shell
pacstrap /mnt base base-devel
#+END_SRC

9. Generate an fstab file
#+BEGIN_SRC shell
genfstab -U /mnt >> /mnt/etc/fstab
#+END_SRC

10. Enter new system
#+BEGIN_SRC shell
arch-chroot /mnt
#+END_SRC

11. Setup timezone
#+BEGIN_SRC shell
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
hwclock --systohc
#+END_SRC

12. Localization
1. Uncomment en_US.UTF-8 UTF-8 in /etc/locale.gen
2. Generate it with:
#+BEGIN_SRC shell
locale-gen
#+END_SRC
3. Create /etc/locale.conf and set LANG variable
#+BEGIN_SRC txt
LANG=en_US.UTF-8
#+END_SRC

4. Set keyboard layout in /etc/vconsole.conf
#+BEGIN_SRC txt
KEYMAP=de-latin1
#+END_SRC


13. Network configuration
1. Edit /etc/hostname with "arch"
2. Edit /etc/hosts
#+BEGIN_SRC txt
127.0.0.1    localhost
::1          localhost
127.0.1.1    arch.localdomain    arch
#+END_SRC

14. Initramfs
#+BEGIN_SRC shell
mkinitcpio -p linux
#+END_SRC

15. Set root password
#+BEGIN_SRC shell
passwd
#+END_SRC

16. Install bootloader
#+BEGIN_SRC sh
pacman -S grub efibootmgr os-prober
mkdir /boot/efi
mount /dev/sda2 /boot/efi
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
mkdir /boot/efi/EFI/BOOT
cp /boot/efi/EFI/GRUB/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI
nano /boot/efi/EFI/startup.nsh
#+END_SRC

Add the following text
#+BEGIN_SRC txt
bcf boot add 1 fs0:\EFI\GRUB\grubx64.efi "My GRUB"
exit
#+END_SRC
#+BEGIN_SRC sh
grub-mkconfig -o /boot/grub/grub.cfg
mkinitcpio -p linux
#+END_SRC

16. Network
#+BEGIN_SRC sh
pacman -S iw wpa_supplicant dialog wpa_actiond
#+END_SRC
17. Reboot

* Post-Installation Setup
** Users & Groups
Add user:
#+BEGIN_SRC shell
useradd -m -G wheel,storage,power -s icm
passwd icm
EDITOR=nano visudo
#+END_SRC
Uncomment whell ALL=(ALL) ALL
#+BEGIN_SRC sh
pacman -S bash-completion
pacman -S mesa
pacman -S xf86-video-intel intel-dri
pacman -S xf86-input-synaptics
pacman -S NetworkManager
pacman -S alsa-utils pulseaudio pavucontrol
#+END_SRC

** Mirrors
Follow [[these pro][these]] procedures.
** AUR Package Manager
Yay is the latest most well written package manager in go that builds and
 installs packages from the AUR.
#+BEGIN_SRC shell
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
#+END_SRC
** Display Drivers
[[https://wiki.archlinux.org/index.php/NVIDIA][here]]
** Xorg Server
#+BEGIN_SRC shell
sudo pacman -S xorg xorg-server xorg-xinit xorg-server-utils
sudo pacman -S xorg-twm xorg-xclock xterm
#+END_SRC
** Gnome & GDM
#+BEGIN_SRC shell
sudo pacman -S gnome gnome-extra
sudo systemctl start gdm.service
sudo systemctl enable gdm.service
#+END_SRC
** Themes
*** Gnome Tweaks
#+BEGIN_SRC shell
sudo pacman -S gnome-tweaks
#+END_SRC
*** Gnome Theme

Setup the major gnome icon, shell and applications theme from one of the
following: (currently I use Paper Icons with Ant Shell and Applications)

1. EvoPop
#+BEGIN_SRC shell
yay -S evopop-gtk-theme
#+END_SRC
2. Arc-Theme
#+BEGIN_SRC shell
yay -S arc-gtk-theme
#+END_SRC
3. Paper
#+BEGIN_SRC shell
yay -S paper-icon-theme-git
#+END_SRC
4. Ant
Clone github repository to /usr/share/themes directory by running:
#+BEGIN_SRC shell
git clone https://github.com/EliverLara/Ant
#+END_SRC
And change the appearence settings with the gnome-tweak-tool.

*** GDM Theme
#+BEGIN_SRC shell
yay -S gdm-themes
#+END_SRC

** Fonts

Installing fonts is a very important step in an arch linux configuration.
Here are a couple of suggestions:
#+BEGIN_SRC shell
sudo pacman -S ttf-dejavu
sudo pacman -S ttf-anonymous-pro
sudo pacman -S ttf-liberation 
sudo pacman -S noto-fonts
#+END_SRC
** Extensions
*** GSConnect

* Applications
** Zsh
1. Oh-my-zsh
#+BEGIN_SRC sh
sudo pacman -S zsh git wget curl vim
sh -c "$(wget -O- https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
#+END_SRC
2. Theme
#+BEGIN_SRC sh
git clone https://github.com/ergenekonyigit/lambda-gitster.git
cd lambda-gitster
cp lambda-gitster.zsh-theme ~/.oh-my-zsh/custom/themes
#+END_SRC
Change ZSH_THEME to "lambda-gitster" in .zshrc.
3. Addons
Install autosuggestions
#+BEGIN_SRC sh
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
#+END_SRC
Add zsh-autosuggestions to plugins
Install zsh-syntax-highlighting
#+BEGIN_SRC sh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
#+END_SRC
Also add it to your plugins list.
4. Base 16 Theme
Clone the main repository:
#+BEGIN_SRC shell
git clone https://github.com/aaron-williamson/base16-gnome-terminal.git ~/.config/base16-gnome-terminal
#+END_SRC
And execute the file containing your selected theme:
#+BEGIN_SRC shell
.config/base16-gnome-terminal/color-scripts/base16-bright.sh
#+END_SRC

** Firefox
1. Install firefox
#+BEGIN_SRC shell
sudo pacman -S firefox
#+END_SRC
2. Add extensions:
- vimiumfx
- keepassxc
- ublock origin
- Setup Search Engines
|---------------------+--------|
| DuckDuckGo          | d      |
| Wikipedia           | w      |
| GitHub              | g      |
| YouTube             | y      |
| Google Maps         | gm     |
| Google Translate    | gt     |
| Leo PT              | l      |
| Leo EN              | l      |
| Leo RU              | Lambda |
| Wiktionary          | ve     |
| imdb                | i      |
| ProxyBay            | p      |
| ArchWiki            | a      |
| Arch Linux Packages | ap     |
| Amazon              | am     |
|---------------------+--------|

4. Furthuer customizations
- Remove title bar
- Disable password completion
- Customize history and cookie saving
** Thunderbird
#+BEGIN_SRC shell
sudo pacman -S thunderbird
#+END_SRC
** ProtonMail Bridge
Needs to be build from scratch. Donwload .pkg from mail.
** MEGASync
Install package with:
#+BEGIN_SRC shell
yay -S megasync
#+END_SRC
And connect Documents/ folder in /home/icm.
** Franz
#+BEGIN_SRC sh
yay -S franz
#+END_SRC
** KeePassXC
#+BEGIN_SRC sh
sudo pacman -S keepassxc
#+END_SRC
** Emacs
#+BEGIN_SRC sh
sudo pacman -S emacs
#+END_SRC
Download emacs and pull the Dot Files repository from github. By typing:
#+BEGIN_SRC sh
git init
git add remote git@github.com:jmpargana/Dot-Files.git
git pull --rebase
#+END_SRC
** Ranger
#+BEGIN_SRC shell
sudo pacman -S ranger
#+END_SRC
Create gnome keybinding:
gnome-terminal -r "ranger"
** Spotify
#+BEGIN_SRC sh
yay -S spotify
#+END_SRC
** Vlc
#+BEGIN_SRC sh
sudo pacman -S vlc
#+END_SRC
** Gnome Logs
#+BEGIN_SRC shell
sudo pacman -S gnome-logs
#+END_SRC

* Programming Languages
** Python
1. Install pip, update it and upgrade (python2 version can always be installed as well)
#+BEGIN_SRC sh
sudo pacman -S python-pip
pip install --upgrade pip
#+END_SRC
2. Install each of the packages. (root permission might be needed)
*** flake8
#+BEGIN_SRC sh
sudo pacman -S flake8
#+END_SRC

*** jedi
#+BEGIN_SRC sh
sudo pacman -S python-jedi
#+END_SRC

*** numpy
#+BEGIN_SRC sh
sudo pacman -S python-numpy
#+END_SRC

*** nltk
#+BEGIN_SRC sh
sudo pacman -S python-nltk
#+END_SRC

*** elpy
Ubuntu elpy package might be available
#+BEGIN_SRC sh
sudo pacman -S emacs-elpy
#+END_SRC

*** autopep8
#+BEGIN_SRC sh
sudo pacman -S autopep8
#+END_SRC

*** rope
#+BEGIN_SRC sh
sudo pacman -S python-rope
#+END_SRC

*** yapf
#+BEGIN_SRC sh
sudo pacman -S yapf
#+END_SRC

*** virtualenv
#+BEGIN_SRC sh
sudo pacman -S python-virtualenv
#+END_SRC

*** jupyter
#+BEGIN_SRC sh
sudo pacman -S jupyter-notebook
#+END_SRC

*** ipython
#+BEGIN_SRC sh
sudo pacman -S ipython
#+END_SRC

*** matplotlib
#+BEGIN_SRC sh
sudo pacman -S python-matplotlib
#+END_SRC

** C++
*** gcc
#+BEGIN_SRC sh
sudo pacman -S gcc
#+END_SRC

*** g++
#+BEGIN_SRC sh
sudo pacman -S g++
#+END_SRC

*** make
#+BEGIN_SRC sh
sudo pacman -S make
#+END_SRC

*** cmake
#+BEGIN_SRC sh
sudo pacman -S cmake
#+END_SRC

*** clang
Install clang across your system
#+BEGIN_SRC sh
sudo pacman -S clang
#+END_SRC
*** irony
This might not work according to your system
#+BEGIN_SRC sh
yay pacman -S emacs-company-irony-git
#+END_SRC

*** silver searcher (for definition jumps)
#+BEGIN_SRC sh
sudo pacman -S the_silver_searcher
#+END_SRC

*** cling
Cling is REPL for C++. Very usefull!
#+BEGIN_SRC sh
yay -S cling-git
#+END_SRC

** JavaScript
*** npm
#+BEGIN_SRC sh
sudo pacman -S nodejs
sudo pacman -S npm
#+END_SRC
*** typescript
#+BEGIN_SRC sh
sudo npm install -g typescript
#+END_SRC
*** tern
#+BEGIN_SRC sh
sudo npm install -g tern
#+END_SRC
*** yarn
#+BEGIN_SRC sh
sudo npm install -g yarn
#+END_SRC
*** meteor
#+BEGIN_SRC sh
curl https://install.meteor.com/ | sh
#+END_SRC

*** mongodb
1. Install mongodb
#+BEGIN_SRC sh
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
sudo apt-get update
sudo apt-get install -y mongodb-org
sudo service mongod start
#+END_SRC
2. Setup emacs for mongo

*** revealjs
#+BEGIN_SRC sh
git clone https://github.com/hakimel/reveal.js/
cd reveal.js
npm install
#+END_SRC

*** prettier
#+BEGIN_SRC sh
sudo pacman -S prettier
#+END_SRC
** Java
#+BEGIN_SRC sh
sudo pacman -S jdk-openjdk openjdk-doc openjdk-src
#+END_SRC

** Haskell
   #+BEGIN_SRC sh
sudo pacman -S ghc
   #+END_SRC

** MySQL
1. Arch Linux official SQL package is [[https://wiki.archlinux.org/index.php/MariaDB][mariadb]]
2. Set root password and create users
3. Setup emacs for MySQL
   
** Go
#+BEGIN_SRC sh
sudo pacman -S go
#+END_SRC

** LaTeX
** MarkDOWN
#+BEGIN_SRC sh
git clone --recursive git://github.com/fletcher/peg-multimarkdown.git
make
#+END_SRC

** Latex
Get all Maths-fonts
#+BEGIN_SRC shell
sudo pacman -S texlive-core texlive-fontsextra
#+END_SRC
#+BEGIN_SRC sh
sudo pacman -S texlive-most texlive-lang biber
#+END_SRC

* Optimizations
** SSH Key
0. Install openssh
#+BEGIN_SRC sh
sudo pacman -S openssh
#+END_SRC
1. Generate key 
#+BEGIN_SRC sh
ssh-keygen -t rsa -b 4096 -C "icmjmp@protonmail.ch"
#+END_SRC
2. Add key to ssh-agent
#+BEGIN_SRC sh
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
#+END_SRC
3. Copy id_rsa.pub to your github account
4. Add ssh key to keepassxc
** Microcode
1. Depending on the processor architecture:
#+BEGIN_SRC shell
sudo pacman -S amd-ucode
sudo pacman -S intel-ucode
#+END_SRC
2. Update the bootloader
#+BEGIN_SRC shell
grub-mkconfig -o /boot/grub/grub.cfg
#+END_SRC
3. Detecting available microcode updates
#+BEGIN_SRC shell
sudo pacman -S intel-ucode iucode-tool
modprobe cpuid
bsdtar -Oxf /boot/intel-ucode.img | iucode_tool -tb -lS -
#+END_SRC
** Silent Boot
1. Add /quiet vga=current vt.global_cursor_default=0/ to your 
bootloader's entries' options.
2. Hide all kernel messages from the console by 
creating /etc/sysctl.d/20-quiet-printk.conf
#+BEGIN_SRC txt
kernel.printk = 3 3 3 3
#+END_SRC
3. Hide agetty reate /etc/systemd/system/getty@tty1.service.d/skip-prompt.conf
#+BEGIN_SRC txt
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --skip-login --nonewline --noissue --autologin username --noclear %I $TERM
#+END_SRC
4. Prevent startx from redirecting output by adding this to .bash_profile
#+BEGIN_SRC sh
[[ $(fgconsole 2>/dev/null) == 1 ]] && exec startx -- vt1 &> /dev/null
#+END_SRC
5. Hide fsck messages during boot by adding systemd to /etc/mkinitcpio.conf:
#+BEGIN_SRC sh
mkinitcpio -p linux
#+END_SRC
6. Do the same in systemd-fsck-root.service and systemd-fsck@.service with:
#+BEGIN_SRC sh
systemctl edit --full systemd-fsck-root.service
systemctl edit --full systemd-fsck@.service
#+END_SRC
#+BEGIN_SRC txt
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/lib/systemd/systemd-fsck
StandardOutput=null
StandardError=journal+console
TimeoutSec=0
#+END_SRC
7. Retain vendor logo from BIOS (not with dual boot)

** Power Management
*** Battery Life
1. Start by installing the powertop package
#+BEGIN_SRC sh
sudo pacman -S powertop
#+END_SRC

2. Create systemd process by editing file /etc/systemd/system/powertop.service
#+BEGIN_SRC txt
[Unit]
Description=Powertop tunings

[Service]
Type=oneshot
ExecStart=/usr/bin/powertop --auto-tune
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
#+END_SRC

3. Start and enable service
#+BEGIN_SRC sh
sudo systemctl start powertop.service
sudo systemctl enable powertop.service
#+END_SRC

4. Prevent innacurate measurement
#+BEGIN_SRC sh
sudo powertop --calibrate
#+END_SRC
*** CPU & Fan
#+BEGIN_SRC sh
yay -S thermald
sudo systemctl enable thermald.service
sudo systemctl start thermald.service
#+END_SRC
** Printer
** Firewall
1. Change /etc/default/ufw 
IPV6=yes 
2. Setup default policies
#+BEGIN_SRC sh
sudo ufw default deny incoming
sudo ufw default allow outgoing
#+END_SRC
3. Allow ssh & gsconnect
#+BEGIN_SRC sh
sudo ufw allow ssh
sudo ufw allow 1176
#+END_SRC
4. Enable UFW on boot
#+BEGIN_SRC sh
sudo ufw enable
#+END_SRC

** Missing firmware
#+BEGIN_SRC sh
yay -S aic94xx-firmware wd719x-firmware
#+END_SRC
** VPN
1. Get openvpn
#+BEGIN_SRC shell
sudo pacman -S openvpn networkmanager-openvpn
#+END_SRC
2. Get openconnect
#+BEGIN_SRC sh
sudo pacman -S openconnect networkmanager-openconnect
#+END_SRC
3. Download nordvpn config files
#+BEGIN_SRC sh
mkdir ~/Documents/.nordvpn
sudo wget https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
sudo pacman -S ca-certificates unzip
unzip ovpn.zip ~/Documents/.nordvpn
#+END_SRC
4. Find best server
[[https://nordvpn.com/de/servers/tools/][here]]
5. Set Goethe Uni Frankfurt VPN
vpn-einwahl.uni-frankfurt.de with CiscoAnyConnect.

** Startup Applications
*** KeePassXc
*** Franz
*** ProtonMail Bridge
*** ThunderBird
*** Emacs
To do so, you need to add an entry in ~/.config/systemd/user/emacs.service
containing:
#+BEGIN_SRC txt
[Unit]
Description=Emacs text editor
Documentation=info:emacs man:emacs(1) https://gnu.org/software/emacs/

[Service]
Type=forking
ExecStart=/usr/bin/emacs --daemon
ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
Environment=SSH_AUTH_SOCK=%t/keyring/ssh
Restart=on-failure

[Install]
WantedBy=default.target
#+END_SRC
And start and enable the systemd process with:
#+BEGIN_SRC shell
systemctl enable --user emacs
systemctl start --user emacs
#+END_SRC
Last but not least, create both a keybinding with
#+BEGIN_SRC sh
emacsclient -c
#+END_SRC
And an alias to launch emacsclient -t in terminal with "ec".
** Others
*** Watchdog
#+BEGIN_SRC sh
yay -S watchdog
sudo systemctl enable watchdog.service
sudo systemctl start watchdog.service
#+END_SRC
* Extras
** Python cProfiler
#+BEGIN_SRC python
import cProfile
import pstats
import io


def profile(fnc):

    """A decorator that uses cProfile to profile a function"""

    def inner(*args, **kwargs):

        pr = cProfile.Profile()
        pr.enable()
        retval = fnc(*args, **kwargs)
        pr.disable()
        s = io.StringIO()
        sortby = 'cumulative'
        ps = pstats.Stats(pr, stream=s).sort_stats(sortby)
        ps.print_stats()
        print(s.getvalue())
        return retval

    return inner
#+END_SRC
** Markdown Template
#+BEGIN_SRC markdown
# Project Title

One Paragraph of project description goes here

## Getting Started

These instructions will get you a copy of the project up and running on your local machine for development and testing purposes. See deployment for notes on how to deploy the project on a live system.

### Prerequisites

What things you need to install the software and how to install them

```
Give examples
```

### Installing

A step by step series of examples that tell you how to get a development env running

Say what the step will be

```
Give the example
```

And repeat

```
until finished
```

End with an example of getting some data out of the system or using it for a little demo

## Running the tests

Explain how to run the automated tests for this system

### Break down into end to end tests

Explain what these tests test and why

```
Give an example
```

### And coding style tests

Explain what these tests test and why

```
Give an example
```

## Deployment

Add additional notes about how to deploy this on a live system

## Built With

* [Dropwizard](http://www.dropwizard.io/1.0.2/docs/) - The web framework used
* [Maven](https://maven.apache.org/) - Dependency Management
* [ROME](https://rometools.github.io/rome/) - Used to generate RSS Feeds

## Contributing

Please read [CONTRIBUTING.md](https://gist.github.com/PurpleBooth/b24679402957c63ec426) for details on our code of conduct, and the process for submitting pull requests to us.

## Versioning

We use [SemVer](http://semver.org/) for versioning. For the versions available, see the [tags on this repository](https://github.com/your/project/tags). 

## Authors

* **Billie Thompson** - *Initial work* - [PurpleBooth](https://github.com/PurpleBooth)

See also the list of [contributors](https://github.com/your/project/contributors) who participated in this project.

## License

This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details

## Acknowledgments

* Hat tip to anyone whose code was used
* Inspiration
* etc
#+END_SRC

